
== React 

=== 1. REACT INTRO

React is a popular library used to create user interfaces. It was built at Facebook to
address some of the challenges associated with "large-scale", "data-driven" websites.

JSX - Javascript Conversion
SCSS - Need to be Preprocess 
Ecmascript New Syntax - Transpiled - Transpiling - BABEL
Redux - Client Data Container 
React Router - Routing 
Jest - Testing 
Webpack - Handling Code splitting, compression, testing
Isomorphic Code - Server Side Rendering 

Fiber - Reimplementation of React Code Algorithm which is aimed at Increasing rendering speed.


===== REACT DEVELOPER TOOLS
react-detector
show-me-the-react 
React Developer Tools





=== 2. EMERGING JS 

Node.js is JavaScript without the browser. It is a runtime environment used to build
full-stack JavaScript applications.

ECMA - European Computer Manufacturer Association.

FEATURES:
LET  - Lexical Variable Scoping  
TEMPLATE STRING - console.log(${name}, ${age});
DEFAULT PARAMETERS
ARROW FUNCTIONS


ES6 OBJECTS AND ARRAYS 
    - SPREAD OPERATOR - "..." - Combine MULTIPLE ARRAYS into one 
    - DESTRUCTING ASSIGNMENTS - Destructring/unpack Value from the Object or Array 
    - OBJECT LITERAL ENHANCEMENT - Process of restructuring and putting values back in Array or Object (Opposite of DESTRUCTURING)
    
    ```
        // NEW
        const skier = {
            name,
            sound,
            powderYell() {
                let yell = this.sound.toUpperCase()
                console.log(`${yell} ${yell} ${yell}!!!`)
            },
            speed(mph) {
                this.speed = mph
                console.log('speed:', mph)
            }
        }
    ```


BABEL - Transpiling - Transpiled the ES6 Syntax that can be interpreted by wide range of browsers.
You can transpile JavaScript directly in the browser using the inline Babel transpiler.
You just include the browser.js file, and any scripts with type="text/babel" will be
converted.




PROMISES
Promises give us a way to make sense out of asynchronous behavior. When making an
asynchronous request, one of two things can happen: everything goes as we hope or
there’s an error.

CLASSES 

MODULES - Easy Decoupling, resolve namespace ambiguity

ES6 MODULES - A JavaScript module is a piece of reusable code that can easily be incorporated into
other JavaScript files.

COMMONJS - CommonJS is the module pattern that is supported by all versions of Node.js.5.
You can still use these modules with Babel and webpack. With CommonJS, JavaScript
objects are exported using module.exports.

The Difference Between ES6 Modules & COMMON JS is that the Common JS does not support IMPORT, it uses "require".
Also while exporting it uses "module.exports={fun1, func2}, compared to ES6 Modules which uses "export / export default infront of methods".
More Info: https://medium.com/computed-comparisons/commonjs-vs-amd-vs-requirejs-vs-es6-modules-2e814b114a0b




=== 3. Functional Programming with JavaScript

Functional Programming came from LAMDA CALCULUS


HIGH ORDER FUNCTIONS - A higher order function is a function that takes a function as an argument, or returns a function.
The first category of higher-order functions are functions that expect other functions
as arguments. Array.map, Array.filter, and Array.reduce all take functions as
arguments. They are higher-order functions.

const userLogs = userName => message =>
console.log(`${userName} -> ${message}`)

Transpiled version of the ABOVE:

"use strict";
var userLogs = function userLogs(a) {
  return function (b) {
    return console.log(a + " -> " + b);
  };
};



const compose = (...fns) =>
(arg) =>
fns.reduce(
(composed, f) => f(composed),
arg
)

Transpiled version of the ABOVE:

"use strict";
var compose = function compose() {
  for (var a = arguments.length, b = Array(a), c = 0; c < a; c++) b[c] = arguments[c];

  return function (d) {
    return b.reduce(function (e, g) {
      return g(e);
    }, d);
  };
};



FIRST-CLASS CITIZENS/MEMBERS - We can say that JavaScript is a functional language because its functions are first-class
citizens. This means that functions are data. They can be saved, retrieved, or flow
through your applications just like variables.


DECLARATIVE PROGRAMMING - Declarative programming is a style of programming where applications
are structured in a way that prioritizes describing what should happen over defining
how it should happen.

IMPERATIVE PROGRAMMING - Imperative programming, or a style of programming that is only concerned with how to achieve
results with code.


FUNCTIONAL CONCEPTS:
    
    Immutability - 
        Object.assign({}, object)
        Using spread "..." operator 

    Purity -
            PURE FUNCTIONS  : A pure function is a function that returns a value that is computed based on its arguments.
            Pure functions take at least one argument and always return a value or
            another function. They do not cause side effects, set global variables, or change anything
            about application state. They treat their arguments as immutable data.

                1. The function should take in at least one argument.
                2. The function should return a value or another function.
                3. The function should not change or mutate any of its arguments.


    Data Transformation
            Array.map
            Array.reduce
            Array.join
            Array.filter 
            Array.reduce 
            Array.reduceRight
            Array.reduceLeft
            Array.slice 
            Array.splice 
            Array.pop
            Array.push 



    Higher-Order Functions 
    Recursion




=== 4. PURE REACT 



=== REFERENCE :

    BOOK NAME : Learning Reacts - Alex Banks and Leo Procello
    REFERENCE : - https://github.com/moonhighway/learning-react