
== React 

=== INTRO

React is a popular library used to create user interfaces. It was built at Facebook to
address some of the challenges associated with "large-scale", "data-driven" websites.

JSX - Javascript Conversion
SCSS - Need to be Preprocess 
Ecmascript New Syntax - Transpiled - Transpiling - BABEL
Redux - Client Data Container 
React Router - Routing 
Jest - Testing 
Webpack - Handling Code splitting, compression, testing
Isomorphic Code - Server Side Rendering 

Fiber - Reimplementation of React Code Algorithm which is aimed at Increasing rendering speed.



===== REACT DEVELOPER TOOLS
react-detector
show-me-the-react 
React Developer Tools


Node.js is JavaScript without the browser. It is a runtime environment used to build
full-stack JavaScript applications.

ECMA - European Computer Manufacturer Association.

FEATURES:
LET  - Lexical Variable Scoping  
TEMPLATE STRING - console.log(${name}, ${age});
DEFAULT PARAMETERS
ARROW FUNCTIONS


ES6 OBJECTS AND ARRAYS 
    - SPREAD OPERATOR - "..." - Combine MULTIPLE ARRAYS into one 
    - DESTRUCTING ASSIGNMENTS - Destructring/unpack Value from the Object or Array 
    - OBJECT LITERAL ENHANCEMENT - Process of restructuring and putting values back in Array or Object (Opposite of DESTRUCTURING)
    
    ```
        // NEW
        const skier = {
            name,
            sound,
            powderYell() {
                let yell = this.sound.toUpperCase()
                console.log(`${yell} ${yell} ${yell}!!!`)
            },
            speed(mph) {
                this.speed = mph
                console.log('speed:', mph)
            }
        }
    ```


BABEL - Transpiling - Transpiled the ES6 Syntax that can be interpreted by wide range of browsers.
You can transpile JavaScript directly in the browser using the inline Babel transpiler.
You just include the browser.js file, and any scripts with type="text/babel" will be
converted.




PROMISES
Promises give us a way to make sense out of asynchronous behavior. When making an
asynchronous request, one of two things can happen: everything goes as we hope or
there’s an error.


BOOK NAME : Learning Reacts - Alex Banks and Leo Procello
REFERENCE : - https://github.com/moonhighway/learning-react