
== React Advance Concepts 

=== Accesibility
    -   aria-label
    -   focus
    -   title tag


=== Code Splitting


    1.  Splitting main bundle into multiple bundles and load them as required by using Code-Splitting Feature of WebPack.
    2.  Code-splitting your app can help you lazy load the code bundles as required. To achieve that 



====  Using dynamic import: Import specific files in the project 

            BEFORE :
            import { add } from './math';
            console.log(add(16, 26));

            AFTER:
            import("./math").then(math => {
                console.log(math.add(16, 26));
            }); 

==== Using React.lazy

The React.lazy function lets you render a dynamic import as a regular component.

        BEFORE:
        import OtherComponent from './OtherComponent';

        function MyComponent() {
        return (
                <div>
                <OtherComponent />
                </div>
            );
        }

        AFTER:
        const OtherComponent = React.lazy(() => import('./OtherComponent'));

        function MyComponent() {
        return (
                <div>
                <OtherComponent />
                </div>
            );
        }

This will automatically load the bundle containing the OtherComponent when this component gets rendered.

React.lazy takes a function that must call a dynamic import(). This must return a Promise which resolves to a module with a default export containing a React component.


====  Suspense 
If the module containing the OtherComponent is not yet loaded by the time MyComponent renders, 
we must show some fallback content while we’re waiting for it to load - such as a loading indicator. 
This is done using the Suspense component.

        const OtherComponent = React.lazy(() => import('./OtherComponent'));

        function MyComponent() {
        return (
                <div>
                    <Suspense fallback={<div>Loading...</div>}>
                        <OtherComponent />
                    </Suspense>
                </div>
            );
        }



====    Error boundaries  
If the other module fails to load (for example, due to network failure), 
it will trigger an error. You can handle these errors to show a nice user experience and manage
recovery with Error Boundaries. Once you’ve created your Error Boundary, you can use it anywhere 
above your lazy components to display an error state when there’s a network error.


            import MyErrorBoundary from './MyErrorBoundary';
            const OtherComponent = React.lazy(() => import('./OtherComponent'));
            const AnotherComponent = React.lazy(() => import('./AnotherComponent'));

            const MyComponent = () => (
            <div>
                <MyErrorBoundary>
                <Suspense fallback={<div>Loading...</div>}>
                    <section>
                    <OtherComponent />
                    <AnotherComponent />
                    </section>
                </Suspense>
                </MyErrorBoundary>
            </div>
            );

            ** A class component becomes an error boundary if it defines either (or both) of the lifecycle methods static getDerivedStateFromError() or componentDidCatch(). 


====   Route-based code splitting


    import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
    import React, { Suspense, lazy } from 'react';

    const Home = lazy(() => import('./routes/Home'));
    const About = lazy(() => import('./routes/About'));


====    Named Exports 
React.lazy currently only supports default exports. If the module you want to import uses 
named exports, you can create an intermediate module that reexports it as the default. This ensures that
tree shaking keeps working and that you don’t pull in unused components.

        // ManyComponents.js
        export const MyComponent = /* ... */;
        export const MyUnusedComponent = /* ... */;

        // MyComponent.js
        export { MyComponent as default } from "./ManyComponents.js";
        
        // MyApp.js
        import React, { lazy } from 'react';
        const MyComponent = lazy(() => import("./MyComponent.js"));





=== Context
Context provides a way to pass data through the component tree without having to pass props down 
manually at every level.

Context is designed to share data that can be considered “global” for a tree of React components, such as the current 
authenticated user, theme, or preferred language.

====    React.createContext

    const MyContext = React.createContext(defaultValue);  //To Set the default Value 

Creates a Context object. When React renders a component that subscribes to this Context object 
it will read the current context value from the closest matching Provider above it in the tree.


====    Context.Provider
    
    <MyContext.Provider value={/* some value */}>

Every Context object comes with a Provider React component that allows consuming components 
to subscribe to context changes.

====    Class.contextType

    class MyClass extends React.Component {
        componentDidMount() {
            let value = this.context;
            /* perform a side-effect at mount using the value of MyContext */
        }
        componentDidUpdate() {
            let value = this.context;
            /* ... */
        }
        componentWillUnmount() {
            let value = this.context;
            /* ... */
        }
        render() {
            let value = this.context;
            /* render something based on the value of MyContext */
        }
    }

    MyClass.contextType = MyContext;


The contextType property on a class can be assigned a Context object created by React.createContext(). 
This lets you consume the nearest current value of that Context type using this.context. You can reference
 this in any of the lifecycle methods including the render function.

 ====   Context.Consumer

    <MyContext.Consumer>
        {value => /* render something based on the context value */}
    </MyContext.Consumer>

A React component that subscribes to context changes. This lets you subscribe to a context 
within a function component.



=== Error Boundaries
A JavaScript error in a part of the UI shouldn’t break the whole app. 
To solve this problem for React users, React 16 introduces a new concept of an “error boundary”.

Error boundaries are React components that catch JavaScript errors anywhere in their child 
component tree, log those errors, and display a fallback UI instead of the component tree that 
crashed. Error boundaries catch errors during rendering, in lifecycle methods, and in constructors 
of the whole tree below them.

A class component becomes an error boundary if it defines either (or both) of the lifecycle methods static getDerivedStateFromError() or componentDidCatch(). Use static getDerivedStateFromError() to render a fallback UI after an error has been thrown. Use componentDidCatch() to log error information.

    class ErrorBoundary extends React.Component {
        constructor(props) {
            super(props);
            this.state = { hasError: false };
        }

        static getDerivedStateFromError(error) {
            // Update state so the next render will show the fallback UI.
            return { hasError: true };
        }

        componentDidCatch(error, info) {
            // You can also log the error to an error reporting service
            logErrorToMyService(error, info);
        }

        render() {
            if (this.state.hasError) {
            // You can render any custom fallback UI
            return <h1>Something went wrong.</h1>;
            }

            return this.props.children; 
        }
    }

Then you can use it as a regular component:

    <ErrorBoundary>
        <MyWidget />
    </ErrorBoundary>


====    How About try/catch?
    
try / catch is great but it only works for imperative code:

    try {
    showButton();
    } catch (error) {
    // ...
    }

However, React components are declarative and specify what should be rendered:

    <Button />

Error boundaries preserve the declarative nature of React, and behave as you would expect. 
For example, even if an error occurs in a componentDidUpdate method caused by a setState
somewhere deep in the tree, it will still correctly propagate to the closest error boundary.


=====   How About Event Handlers?

Error boundaries do not catch errors inside event handlers.

React doesn’t need error boundaries to recover from errors in event handlers. 
Unlike the render method and lifecycle methods, the event handlers don’t happen during 
rendering. So if they throw, React still knows what to display on the screen.

If you need to catch an error inside event handler, use the regular JavaScript try / catch statement:

        class MyComponent extends React.Component {
            constructor(props) {
                super(props);
                this.state = { error: null };
                this.handleClick = this.handleClick.bind(this);
            }

            handleClick() {
                try {
                // Do something that could throw
                } catch (error) {
                this.setState({ error });
                }
            }

            render() {
                if (this.state.error) {
                return <h1>Caught an error.</h1>
                }
                return <div onClick={this.handleClick}>Click Me</div>
            }
        }


=== Forwarding Refs
Ref forwarding is a technique for automatically passing a ref through a component to one of its children. 
This is typically not necessary for most components in the application. However, it can be useful for some
kinds of components, especially in reusable component libraries. 


REFERENCE : https://reactjs.org/docs/context.html
