== Spring 
Spring Framework is a Java platform that provides comprehensive infrastructure support for 
developing Java applications. Spring handles the infrastructure so you can focus on your application.


** Spring is unopinionated, 
** Spring Boot takes an opinionated view of the platform and libraries, letting us get started quickly

==== What is Spring 
Simply put, the Spring framework provides comprehensive infrastructure support for developing 
Java applications.

It’s packed with some nice features like Dependency Injection and out of the box modules like:

- Spring JDBC
- Spring MVC
- Spring Security
- Spring AOP
- Spring ORM
- Spring Test


==== Spring Framework
It supports declarative transaction management, remote access to your logic through RMI or 
web services, and various options for persisting your data. It offers a full-featured MVC 
framework, and enables you to integrate AOP transparently into your software.

Spring is designed to be non-intrusive, meaning that your domain logic code generally has no
dependencies on the framework itself. In your integration layer (such as the data access layer), some
dependencies on the data access technology and the Spring libraries will exist. However, 
it should be easy to isolate these dependencies from the rest of your code base.

===== Modules
The Spring Framework consists of features organized into about 20 modules. These modules are grouped
into Core Container, Data Access/Integration, Web, AOP (Aspect Oriented Programming),
Instrumentation, and Test.


===== Dependency injection (DI) -> Inversion of Control (IoC) -> Service Locator Pattern

===== Constructor-based or setter-based DI ?

==== Scope 
- Singelton  : default 
- Prototype
- Request
- Session
- Global Session 

* Bean Scope per Ioc Container.
* As a rule, use the prototype scope for all stateful beans and the singleton scope for stateless beans.


==== Bean Life Cycle 
A bean life cycle includes the following steps. 

1. Within IoC container, a spring bean is created using class constructor. 

2. Now the dependency injection is performed using setter method. 

3. Once the dependency injection is completed, BeanNameAware.setBeanName() is called. It sets the 
    name of bean in the bean factory that created this bean. 

4. Now < code>BeanClassLoaderAware.setBeanClassLoader() is called that supplies the bean class 
    loader to a bean instance. 

5. Now < code>BeanFactoryAware.setBeanFactory() is called that provides the owning factory to a 
    bean instance. 

6. Now the IoC container calls BeanPostProcessor.postProcessBeforeInitialization on the bean. 
    Using this method a wrapper can be applied on original bean. 

7. Now the method annotated with @PostConstruct is called. 

8. After @PostConstruct, the method InitializingBean.afterPropertiesSet() is called. 

9. Now the method specified by init-method attribute of bean in XML configuration is called. 

10. And then BeanPostProcessor.postProcessAfterInitialization() is called. It can also be used to
    apply wrapper on original bean. 

11. Now the bean instance is ready to be used. Perform the task using the bean. 

12. Now when the ApplicationContext shuts down such as by using registerShutdownHook() then 
    the method annotated with @PreDestroy is called. 

13. After that DisposableBean.destroy() method is called on the bean. 

14. Now the method specified by destroy-method attribute of bean in XML configuration is called. 

15. Before garbage collection, finalize() method of Object is called.