=== Kubernetes - Desired State Management 

Kubernetes (K8s) is an open-source system for automating deployment, scaling,
and management of containerized applications.

    K8's cluster Services 
    kubnet Workers 

    pod - Smallest unit of deployment - One or multiple running containers / Image details and Replicas information.
    *Can have multiple pods 
    A Kubernetes pod is a group of containers that are deployed together on the same host. If you frequently deploy 
    single containers, you can generally replace the word "pod" with "container" and accurately understand the concept

    Kubernetes Features :

        - Service discovery and load balancing
        - Automatic bin packing
        - Storage orchestration
        - Self-healing
        - Automated rollouts and rollbacks
        - Secret and configuration management
        - Batch Execution
        - Horizentol Scaling


Docker is a platform and tool for building, distributing, and running Docker containers. ... 
Kubernetes is a container orchestration system for Docker containers that is more extensive 
than Docker Swarm and is meant to coordinate clusters of nodes at scale in production in an efficient manner.

===== Create Cluster 

Kubernetes coordinates a highly available cluster of computers that are 
connected to work as a single unit.

A Kubernetes cluster consists of two types of resources:
    -   The Master coordinates the cluster
    -   Nodes are the workers that run applications

Minikube - Minikube is a tool that makes it easy to run Kubernetes locally. 
Minikube runs a single-node Kubernetes cluster inside a Virtual Machine (VM)



    minikube version
    
    minikube start 





==== Pre Requisite 
    - Windows Powershell (For Windows) (Version >=5.1)
    - Enable NotePad for vi commands. 
        new-alias vi notepad 

      The above command will enable Powershell to use notepad editor anytime we run "vi" command.

    

==== Conternazation with Kubernetes -
A container is defined as a collection of software processes unified
by one namespace with access to an operating system kernel that it shares
with other containers and little or no access between them.

=====   Kubernetes -
the most popular open-source container orchestrator available today. 



==== REFERENCE
    https://thenewstack.io/kubernetes-vs-docker-swarm-whats-the-difference/
    https://hackernoon.com/kubernetes-vs-docker-swarm-a-comprehensive-comparison-73058543771e
