

==== Define web service protocol stack and its layers?

Web service protocol stack consists of 4 layers. This can be described as follows

1) Service transport: This is the first layer which helps in transporting XML messages between various client applications. This layer commonly uses the below-mentioned protocols:

HTTP(Hypertext Transport Protocol)
SMTP(Simple Mail Transport Protocol)
FTP(File Transfer Protocol)
BEEP(Block Extensible Exchange Protocol)

2) XML messaging: This layer is based on the XML model where messages are encoded in common XML format which is easily understood by others. This layer includes

XML-RPC
SOAP(Simple Object Access Protocol)

3) Service description: This layer contains description like location, available functions, and data types for XML messaging which describes the public interface to a specific web service. This layer includes:

WSDL(Web Service Description Language)

4) Service discovery: This layer is responsible for providing a way to publish and find web services 
over the web. This layer includes:

UDDI(Universal Description, Discovery, and Integration)


==== What are the advantages of Web Services?
Some of the advantages of web services are:

Interoperability: Web services are accessible over network and runs on HTTP/SOAP protocol and 
uses XML/JSON to transport data, hence it can be developed in any programming language. 
Web service can be written in java programming and client can be PHP and vice versa.

Reusability: One web service can be used by many client applications at the same time.

Loose Coupling: Web services client code is totally independent with server code, so we 
have achieved loose coupling in our application.

Easy to deploy and integrate: just like web applications. Multiple service versions can be 
running at same time.


==== Compare SOAP and REST web services?

SOAP is a standard protocol for creating web services.	
REST is an architectural style to create web services.

SOAP is acronym for Simple Object Access Protocol.	
REST is acronym for REpresentational State Transfer.

SOAP uses WSDL to expose supported methods and technical details.	
REST exposes methods through URIs, there are no technical details.

SOAP web services and client programs are bind with WSDL contract	
REST doesn’t have any contract defined between server and client

SOAP web services and client are tightly coupled with contract.	
REST web services are loosely coupled.

SOAP learning curve is hard, requires us to learn about WSDL generation, client stubs creation etc.	
REST learning curve is simple, POJO classes can be generated easily and works on simple HTTP methods.

SOAP supports XML data format only	
REST supports any data type such as XML, JSON, image etc.

SOAP web services are hard to maintain, any change in WSDL contract requires us to 
    create client stubs again and then make changes to client code.	
REST web services are easy to maintain when compared to SOAP, a new method can 
    be added without any change at client side for existing resources.

SOAP web services can be tested through programs or software such as Soap UI.	
REST can be easily tested through CURL command, Browsers and extensions such as Chrome Postman.



==== What is difference between SOA and Web Services?
Service Oriented Architecture (SOA) is an architectural pattern where 
applications are designed in terms of services that can be accessed through 
communication protocol over network. SOA is a design pattern and doesn’t go into implementation.

Web Services can be thought of as Services in SOAP architecture and providing means to 
implement SOA pattern.



==== REST 

SOAP and REST can't be compared directly, since the first is a protocol (or at least tries to be) 
and the second is an architectural style. This is probably one of the sources of confusion around it, 
since people tend to call REST any HTTP API that isn't SOAP.

I think these are the crucial points to understand what REST is about, and how it differs from SOAP:

REST is protocol independent. It's not coupled to HTTP. Pretty much like you can follow an ftp link 
on a website, a REST application can use any protocol for which there is a standardized URI scheme.

REST is not a mapping of CRUD to HTTP methods. Read this answer for a detailed explanation on that.

REST is as standardized as the parts you're using. Security and authentication in HTTP are 
standardized, so that's what you use when doing REST over HTTP.

REST is not REST without hypermedia and HATEOAS. This means that a client only knows the entry 
point URI and the resources are supposed to return links the client should follow. Those fancy 
documentation generators that give URI patterns for everything you can do in a REST API miss the 
point completely. They are not only documenting something that's supposed to be following the standard, 
but when you do that, you're coupling the client to one particular moment in the evolution of the API, 
and any changes on the API have to be documented and applied, or it will break.

REST is the architectural style of the web itself. When you enter Stack Overflow, you know what a User, 
a Question and an Answer are, you know the media types, and the website provides you with the links to 
them. A REST API has to do the same. If we designed the web the way people think REST should be done, 
instead of having a home page with links to Questions and Answers, we'd have a static documentation 
explaining that in order to view a question, you have to take the URI stackoverflow.com/questions/<id>, 
replace id with the Question.id and paste that on your browser. That's nonsense, but that's what many 
people think REST is

REFERENCE : https://stackoverflow.com/questions/19884295/soap-vs-rest-differences



===== Rest Design Guideline
Some soft guidelines for designing a REST architecture:

1. Do not use "physical" URLs. A physical URL points at something physical -- e.g., 
   an XML file: "http://www.acme.com/inventory/product003.xml". A logical URL does not 
   imply a physical file: "http://www.acme.com/inventory/product/003".
   Sure, even with the .xml extension, the content could be dynamically generated. 
   But it should be "humanly visible" that the URL is logical and not physical.

2. Queries should not return an overload of data. If needed, provide a paging mechanism. 
   For example, a "product list" GET request should return the first n products (e.g., the first 10), 
   with next/prev links.

3. Even though the REST response can be anything, make sure it's well documented, and do not 
   change the output format lightly (since it will break existing clients).
   Remember, even if the output is human-readable, your clients aren't human users.
   If the output is in XML, make sure you document it with a schema or a DTD.

4. Rather than letting clients construct URLs for additional actions, include the actual URLs 
   with REST responses. For example, a "product list" request could return an ID per product, 
   and the specification says that you should use http://www.acme.com/product/PRODUCT_ID to get 
   additional details. That's bad design. Rather, the response should include the actual URL with 
   each item: http://www.acme.com/product/001263, etc.
   Yes, this means that the output is larger. But it also means that you can easily direct clients 
   to new URLs as needed, without requiring a change in client code.

5. GET access requests should never cause a state change. Anything that changes the server state 
   should be a POST request (or other HTTP verbs, such as DELETE).



===== ROA (REST Oriented Architecture) 
===== SOA (Service Based Architecture)



==== Guiding Principles of REST
1. Client–server – By separating the user interface concerns from the data storage concerns, 
    we improve the portability of the user interface across multiple platforms and improve 
    scalability by simplifying the server components.

2. Stateless – Each request from client to server must contain all of the information necessary 
    to understand the request, and cannot take advantage of any stored context on the server. 
    Session state is therefore kept entirely on the client.

3. Cacheable – Cache constraints require that the data within a response to a request be implicitly 
   or explicitly labeled as cacheable or non-cacheable. If a response is cacheable, then a client 
   cache is given the right to reuse that response data for later, equivalent requests.

4. Uniform interface – By applying the software engineering principle of generality to the component 
   interface, the overall system architecture is simplified and the visibility of interactions is 
   improved. In order to obtain a uniform interface, multiple architectural constraints are needed to 
   guide the behavior of components. REST is defined by four interface constraints: identification of 
   resources; manipulation of resources through representations; self-descriptive messages; and, 
   hypermedia as the engine of application state.

5. Layered system – The layered system style allows an architecture to be composed of hierarchical 
    layers by constraining component behavior such that each component cannot “see” beyond the immediate 
    layer with which they are interacting.

6. Code on demand (optional) – REST allows client functionality to be extended by downloading and 
    executing code in the form of applets or scripts. This simplifies clients by reducing the number of 
    features required to be pre-implemented.


==== REFERENCE 
https://restfulapi.net
http://rest.elkstein.org/
https://en.wikipedia.org/wiki/Representational_state_transfer
https://dzone.com/articles/securing-rest-apis-with-client-certificates